### ISSUE TITLE
Error in  movies list api

### ISSUE THREAD

**Issue by ayalma** [abbas-oveissi/MoviesApi_ir#1]
Hi , I was just trying to use this api in flutter and faced to String casting to int error
and after some debugging  i found out that The api return current_page = "2" in this request response `http://moviesapi.ir/api/v1/movies?page=2` 
like that `metadata":{"current_page":"2","per_page":10,"page_count":25,"total_count":250}`

**Comment by abbas-oveissi** [comment]
ببخشید از اینکه اذیت شدید و مرسی از اینکه خبرم کردید. مشکل حل شد و از این به بعد همیشه رشته برمیگرده.
