### ISSUE TITLE
Fonts not found in website

### ISSUE THREAD

**Issue by SamaneYaghoobi** [abbas-oveissi/MoviesApi_ir#4]
In movies list api site, Vazir font doesn't load because its css file gets 404 not found.
I find that in [www.moviesapi.ir/vendor ](http://www.moviesapi.ir/vendor/) there is no Vazir font file, but there is IranSans.
So I can change the website font to IranSans and send a pull request if you want.

![image](https://user-images.githubusercontent.com/22401814/67427962-0bc31f00-f5ea-11e9-9e76-1d22c391e9cc.png)

**Comment by abbas-oveissi** [comment]
دلیلش این بوده که چون فونت ایران سنس رو نمیشد توی ریپو بذارم، توی ریپو از همون وزیر استفاده کردم و سی‌اس‌اس هم به همون وزیر اشاره میکنه.
فقط توی سایت خودم میخواستم از ایران‌سنس استفاده کنم که الان بنظرم لزومی نداره، همون فونت وزیر خوبه. فکرکنم فو بذارم همه چی اوکی بشه، آره؟

**Comment by SamaneYaghoobi** [comment]
@abbas-oveissi بله درسته فونت وزیر رو توی پوشه وندور بزارید فیکس میشه. ممنون
